directories:
  output: release
  buildResources: build
appId: com.votecounter.app
productName: Vote Counter
mac:
  category: public.app-category.utilities
  target: dmg
files:
  - filter:
      - dist/**/*
      - electron/**/*
electronVersion: 28.3.3
